messages:
  # Сообщение которое будет выводиться если команду ввели из консоли
  consoleUse: "&#fb0000Только игроки могут использовать эту команду!"
  # Сообщение которое будет выводиться если ввели меньше или больше 1 аргумента
  use: "&fИспользование: &#4ab6fb/sex <ник>"
  # Сообщение которое будет выводиться если игрок которого указали в команде не найден
  notFound: "&#fb0000Игрок не найден!"
  # Сообщение которое будет выводиться если игрок слишком далеко от игрока указанного в команде
  far: "&fИгрок &#4ab6fb%target% &fслишком далеко!"

settings:
  # Дистанция на которой должен находиться игрок который ввел команду от того кого ввел
  distance: 10

  title:
    # Плейсхолдеры:
    # %target% - ник игрока который ввели в команде
    player:
      # Титл который будет выводиться игроку который ввел команду
      title: "&fТы трахнул"
      # Сабтитл который будет выводиться игроку который ввел команду
      subtitle: "&fигрока &#4ab6fb%target%"

    # Плейсхолдеры:
    # %player% - ник игрока который ввел команду
    target:
      # Титл который будет выводиться игроку ник которого ввели в команде
      title: "&fТебя трахнул"
      # Сабтитл который будет выводиться игроку ник которого ввели в команде
      subtitle: "&fигрок &#4ab6fb%player%"